version: '3.4'

services:
  roi-calculator.ui:
    image: ${DOCKER_REGISTRY-}abc-roi-calculator-ui
    ports:
        - "5001:443"
        - "5000:80"
    build:
      context: .
      dockerfile: src/client/AbcRoiCalculator.UI/Dockerfile
    depends_on:
        - roi-calculator.api

  roi-calculator.api:
    image: ${DOCKER_REGISTRY-}abc-roi-calculator-api
    ports:
        - "6001:443"
        - "6000:80"
    build:
      context: .
      dockerfile: src/server/AbcRoiCalculator.API/Dockerfile
    depends_on:
        - exchange-rates-service

  exchange-rates-service:
    image: ${DOCKER_REGISTRY-}exchange-rates-service
    ports:
        - "50051:443"
        - "50000:80"
    build:
      context: .
      dockerfile: src/server/ExchangeRatesService/Dockerfile
   

