export const actionNames = {
    CHANGE_TAB : 'CHANGE_TAB',
    REQUEST_ROI_CALCULATION: 'REQUEST_ROI_CALCULATION',
    RECEIVE_ROI_CALCULATION : 'RECEIVE_ROI_CALCULATION',
    REQUEST_INVESTMENT_OPTIONS :  'REQUEST_INVESMENT_OPTIONS',
    RECEIVE_INVESTMENT_OPTIONS : 'RECEIVE_INVESTMENT_OPTIONS'
};
